### ISSUE TITLE
Use on Windows

### ISSUE THREAD

**Issue by poggo96** [kthohr/optim#19]
Is there a possibility to use the library on Windows ? 
I have built a header only version on a Linux system with the command "./configure --header-only-version". I copied it to Windows and want to use it now. With the compiler msvc2015. 
I also have Armadillo only as a header only variant. This is also in the program directory of my software. 

How do I get OptimLib to use Armadillo from the same workdirectory and get it running in general ? 

Since there is no DLL or LIB file available, the library should be included everywhere and compiler independent.

**Comment by tzcskys** [comment]
@poggo96  Hi, have you solved this problem? i also want to use optimlib on windows but I am not sure it can run properly, could you please help to share some experiences? thanks a lot.

**Comment by poggo96** [comment]
You can build the header-only library on Linux. (virtual machine). Then you just put the built library in your workspace and also the Armadillo lib. Include both in your software "armadillo" and then "optim.hpp". 
There should be some error messages. For example: "error: C2039: 'function': is not a member of 'std
I have included the following headers before optim. Then it worked: 
#include <stdlib.h>
#include <cstdlib.h>
#include <functional>
#include <iostream>

#include "armadillo"
#include "optim.hpp"
(I don't know if all these are necessary)

**Comment by tzcskys** [comment]
Thank you so much for your kindly reply.

I have tried to firstly install armadillo on win10 (works great) and build the header-only optimlib in ubuntu (I use conda to install cmake, libopenblas and liblapack before install Header-only optimlib). And then copy the header-only folder into my win10 and include it in my vs2017 solution. However, there are so many errors about `#include "optim.hpp"`, for example,  identifier "Vec_t" is underfined in sumt.hpp of optimlib. I am not sure the reason now. I will update if I solve it and would appreciate it a lot if anyone could share it when you meet and solve the same problem.

**Comment by tzcskys** [comment]
> 
> 
> Thank you so much for your kindly reply.
> 
> I have tried to firstly install armadillo on win10 (works great) and build the header-only optimlib in ubuntu (I use conda to install cmake, libopenblas and liblapack before install Header-only optimlib). And then copy the header-only folder into my win10 and include it in my vs2017 solution. However, there are so many errors about `#include "optim.hpp"`, for example, identifier "Vec_t" is underfined in sumt.hpp of optimlib. I am not sure the reason now. I will update if I solve it and would appreciate it a lot if anyone could share it when you meet and solve the same problem.

actually, just add `#define OPTIM_ENABLE_ARMA_WRAPPERS` before `#include "optim.hpp"`, and it works...

**Comment by poggo96** [comment]
I worked with the armadillo header only lib. so I didn't have the problems with #define OPTIM_ENABLE_ARMA_WRAPPERS. But nice to hear that it works.
