### ISSUE TITLE
Wrapping optimLib to an Rcpp/RcppArmadillo R package

### ISSUE THREAD

**Issue by jchiquet** [kthohr/optim#2]
Hi,

I have being installing your library with no difficulty on a Linux/Ubuntu system and manage to run both examples (Ackley's function and logistic regression) : thank you very much for your work.

Now, I would like to access optim for developing R packages with Rcpp/RcppArmadillo. I am thus trying to wrap your library to R via an R package, [in an attempt that can be found there](https://github.com/jchiquet/optimLibR). I hope it is ok to you.

To do that, I put the headers of optim into inst/include/ and the cpp files into src/. Then I tried to link everything in the src/Makevars files, and the package installation (including compilation of optim) is fine (at least, the package can be installed). The Makevars can be found there :

https://github.com/jchiquet/optimLibR/blob/414015b08a5e316de17b1e0b5385718abd23da6a/src/Makevars#L1-L41

Then I tried to create two small Rcpp functions for both Ackley and logit examples, starting with the following lines

```c++
// [[Rcpp::depends(RcppArmadillo)]]
// [[Rcpp::plugins(cpp11)]]
#define USE_RCPP_ARMADILLO
#include "optim.hpp"
```

However, when I call the corresponding R functions, I get the following Armadillo errors in R which I do not have wheh running them in 'pure' C++ (I am pretty sure it is not a syntax problem, the Rcpp code and the original C++ code are hopefully identical, except for the headers).

```r
> library(optimLibR)
> ackley_function()

error: arma::memory::acquire(): out of memory
```

```r
> library(optimLibR)
> logit_optimLib()

error: Mat::init(): requested size is not compatible with column vector layout
```

If you could have a quick glance, at least to check that the flag and libs in the Makevars are correctly set for optimr equirements, it would help a lot and I would be happy to use your library in my future R packages. 

Thanks for your time

**Comment by kthohr** [comment]
You need to compile the core OptimLib files with the `USE_RCPP_ARMADILLO` flag. Otherwise you are mixing Armadillo and RcppArmadillo definitions, which leads to the error.

Change your Makevars file here:
```
OPTIMLIB_CXXFLAGS = -I../inst/include -DUSE_RCPP_ARMADILLO
```
And remove the hard define in logit_reg.cpp and ackley_function.cpp. I use a similar setup in one of my packages:

https://github.com/kthohr/BMR/blob/master/src/Makevars

With this change, the examples ran just fine for me.

**Comment by kthohr** [comment]
@jchiquet - Did this resolve the issue for you?

**Comment by jchiquet** [comment]
@kthohr yes, it solved my problem. Thanks a lot, a sorry for the delay (out of the office...).
