### ISSUE TITLE
NM Eigen Aliasing Bug

### ISSUE THREAD

**Issue by alitteneker** [kthohr/optim#22]
See line 149 of `nm.cpp` which currently reads as follows.
`simplex_points = OPTIM_MATOPS_ROWS(simplex_points, sort_vec);`

If using Eigen as a linear algebra library, this presents an [aliasing problem](https://eigen.tuxfamily.org/dox/group__TopicAliasing.html), which makes the result of this operation dramatically incorrect. For example, try it with the Booth demo listed in the documentation. It will give something like (0,0.25), far away from the correct (1,3).

Fortunately, there's a pretty easy fix. Just add an eval to the line as follows to force Eigen to behave as expected.
`simplex_points = OPTIM_MATOPS_EVAL(OPTIM_MATOPS_ROWS(simplex_points, sort_vec));`

**Comment by kthohr** [comment]
Thanks for catching that! Just pushed a fix.
