### ISSUE TITLE
cannot build it with eigen

### ISSUE THREAD

**Issue by Horizon-42** [kthohr/optim#23]
./configure -i "usr/local" -l eigen -p 
return
Summary:
  - OS:            linux-gnu
  - C++ compiler:  g++
  - Build version: release

  - OPTIM_LINEAR_ALG_LIB set to: eigen
  - OPTIM_MATLIB_INCLUDE_PATH set to:
    
  - BLAS and Lapack libraries set to:
    -lblas -llapack

  - OpenMP features: enabled
  - optimization flags:
    -fPIC -O3 -march=native -ffp-contract=fast -flto -DNDEBUG -fopenmp

  - OptimLib install path:
    usr/local

  - Additional notes:

Configuration completed. Creating Makefile... done.

but when I run make, it fails, return
g++ -std=c++11 -Wall -fPIC -O3 -march=native -ffp-contract=fast -flto -DNDEBUG -fopenmp -DOPTIM_ENABLE_EIGEN_WRAPPERS -I -I./include src/line_search/more_thuente.cpp -c -o src/line_search/more_thuente.o
src/line_search/more_thuente.cpp:27:10: fatal error: optim.hpp: no such file
 #include "optim.hpp"
          ^~~~~~~~~~~
compilation terminated.
make: *** [Makefile:54：src/line_search/more_thuente.o]

**Comment by kthohr** [comment]
You need to set ``EIGEN_INCLUDE_PATH``. I've updated the configure script to throw an error if this is not found.

**Comment by Horizon-42** [comment]
thank you, now it can compile, but throw an error:
./include/misc/matrix_ops/access.hpp:35:50: error: ‘all’ is not a member of ‘Eigen’
     #define OPTIM_MATOPS_ROWS(x, v) (x)(v,Eigen::all) // v is a vector
                                                  ^
./include/misc/matrix_ops/eval.hpp:30:35: note: in definition of macro ‘OPTIM_MATOPS_EVAL’
     #define OPTIM_MATOPS_EVAL(x) (x).eval()
                                   ^
src/unconstrained/nm.cpp:149:44: note: in expansion of macro ‘OPTIM_MATOPS_ROWS’
         simplex_points = OPTIM_MATOPS_EVAL(OPTIM_MATOPS_ROWS(simplex_points, sort_vec));
                                            ^~~~~~~~~~~~~~~~~

I use eigen3, don't know if it's ik

**Comment by kthohr** [comment]
When you ran `configure` what was the output under ``OPTIM_MATLIB_INCLUDE_PATH set to:``

**Comment by Horizon-42** [comment]
OPTIM_MATLIB_INCLUDE_PATH set to:
    /usr/include/eigen3

/usr/include/eigen3 is EIGEN_INCLUDE_PATH

**Comment by Horizon-42** [comment]
compile failed when it run:
g++ -std=c++11 -Wall -fPIC -O3 -march=native -ffp-contract=fast -flto -DNDEBUG -fopenmp -DOPTIM_ENABLE_EIGEN_WRAPPERS -I/usr/include/eigen3 -I./include src/unconstrained/nm.cpp -c -o src/unconstrained/nm.o

**Comment by kthohr** [comment]
Sounds like an issue with your installation of Eigen.

I just pulled the latest version of Eigen from GitLab:

https://gitlab.com/libeigen/eigen

And the library compiled without issue.

As a sanity check, you could try the following:

```
cd ~/Desktop
git clone https://gitlab.com/libeigen/eigen.git
export EIGEN_INCLUDE_PATH="${PWD}/eigen"
```

Then change back to the directory where you've pulled OptimLib and run `./configure -l eigen && make` again.

**Comment by Horizon-42** [comment]
finally it build success 
but when i use the lib to compile example, it throw a lot of errors, like:
/include/misc/matrix_ops/get_sort_index.hpp:22:1: error: ‘VecInt_t’ does not name a type; did you mean ‘uint_t’?
 VecInt_t
I don't know what wrong?

**Comment by kthohr** [comment]
You need to include an example of what you're trying to compile, along with the compiler options.

**Comment by kthohr** [comment]
Try the same example again with

```cpp
#define OPTIM_ENABLE_EIGEN_WRAPPERS
#include "optim.hpp"
```

**Comment by Horizon-42** [comment]
thank you, it worked.
thank you for you patient, I should read the docs first.

**Comment by kthohr** [comment]
No worries; thanks for pointing out some gaps in the build process and docs. Feel free to reopen if you encounter any other build-related errors.

**Comment by Horizon-42** [comment]
and i found a small iusse when build test
it throw error when i build test like this:

**newton_logit_reg.cpp:115:67: error: ‘std::chrono’ has not been declared**

I just add #include <chrono> to fix it.
