### ISSUE TITLE
Incorrect value transfer

### ISSUE THREAD

**Issue by poggo96** [kthohr/optim#25]
If I pass an Arma::vector (init_vals) to an optimization function with zeros only, values unequal to zero are passed. 
There are values like 0.02678 etc.

**Comment by kthohr** [comment]
I need an actual example to understand the issue.

**Comment by titovmaxim** [comment]
Seems like optimizer is doing a goo job :) I mean it starts to change initial values to find the best solutions. Why do you expect that initial values will be passed to opt_func unchanged?
