### ISSUE TITLE
Can not install the package successfully

### ISSUE THREAD

**Issue by GreatGareth** [kthohr/optim#26]
`local@MacBook-Pro` optim % ./configure -l arma -p

OptimLib Configuration

Summary:
  - OS:            darwin19
  - C++ compiler:  g++
  - Build version: release

  - OPTIM_LINEAR_ALG_LIB set to: arma
  - OPTIM_MATLIB_INCLUDE_PATH set to:
    /Users/local/armadillo-code
  - BLAS and Lapack libraries set to:
    -framework Accelerate

  - OpenMP features: enabled
  - optimization flags:
    -O3 -march=native -ffp-contract=fast -flto -DNDEBUG -fopenmp

  - OptimLib install path:
    /Users/local/optim

  - Additional notes:

Configuration completed. Creating Makefile... done.

local@MacBook-Pro optim % make
g++ -std=c++11 -Wall -O3 -march=native -ffp-contract=fast -flto -DNDEBUG -fopenmp -DOPTIM_ENABLE_ARMA_WRAPPERS -DARMA_NO_DEBUG -I/Users/local/armadillo-code -I./include src/line_search/more_thuente.cpp -c -o src/line_search/more_thuente.o`

I am currently working on some constraint quadratic optimization problem and just try to install your repo on my Mac. However, when i tried to install it, there are some error message about
"clang: error: unsupported option '-fopenmp'
make: *** [src/line_search/more_thuente.o] Error 1".  

It will be really helpful if you could help me take a look or give me any guidance. Thanks so much for your time and looking forward to hearing from you.

**Comment by kthohr** [comment]
You enabled OpenMP features but are using a compiler that doesn't not support it. Drop the `-p` option.
