### ISSUE TITLE
Passing "optim::algo_settings_t" object makes the optimizer crash

### ISSUE THREAD

**Issue by Davar1990** [kthohr/optim#27]
Hi, 

First I'd like to thank you for creating such a wonderful library. I have created a simple example to learn how to use your library the right way. For example, I tried to estimate the parameters of the quadratic function `y = 2 * x ^ 2 - 3 * x + 7` So the weights should be estimated as `[2 -3  7]` 

When I use the line `bool success = optim::bfgs(w, quadratic, &data);` everything seems to be working correctly and the weights are estimated as expected. Yet when I try to manipulate the optimization settings by simply using the block below
```
optim::algo_settings_t settings;
settings.iter_max = 500;
bool success = optim::bfgs(w, quadratic, &data, settings);
```
the program crashes without even returning a success flag. The following is the code I have written. I would very much appreciate your help. 

Thanks,
Davar

```
#include "optim.hpp"
#include <iostream> 

using std::cout;
using std::endl;
using std::vector;

struct Data {
    arma::vec x;
    arma::vec y;
};

double quadratic(const arma::vec& w, arma::vec* grad, void* opt_data) {

    Data* data = reinterpret_cast<Data*>(opt_data);
    arma::vec x = data->x;
    arma::vec y = data->y;

    double f = 0;
    (*grad)(0) = (*grad)(1) = (*grad)(2) = 0;

    for (int i = 0; i < x.n_elem; i++) {

        double t = y(i) - (w(0) * pow(x(i), 2) + w(1) * x(i) + w(2));
        f += pow(t, 2);

        (*grad)(0) += -2 * pow(x(i), 2) * t;
        (*grad)(1) += -2 * x(i) * t;
        (*grad)(2) += -2 * t;

    }

    return f;
}

int main(){

    int numOfObservations = 100;
    arma::vec x(numOfObservations, arma::fill::randn);
    arma::vec y(numOfObservations);
    for (int i = 0; i < numOfObservations; i++) {
        y(i) = 2 * pow(x[i], 2) - 3 * x[i] + 7;
    }
    Data data;
    data.x = std::move(x);
    data.y = std::move(y);

    int numOfDims = 3;
    arma::vec w(numOfDims, arma::fill::zeros);

    bool success = optim::bfgs(w, quadratic, &data);

    //optim::algo_settings_t settings;
    //settings.iter_max = 500;
    //bool success = optim::bfgs(w, quadratic, &data, settings);

    cout << "success = " << success << " --> w = " << w.t() << endl;

    return 0;
}


```

**Comment by Davar1990** [comment]
I have narrowed down the line that causes the issue. It's in the file `error_reporting.ipp` at line `80` which is `        settings_inp->opt_fn_value     = opt_objfn(x_p,nullptr,opt_data);`. If I comment it out, it starts working. If I leave it commented out, wouldn't it cause any issues? Please note I'm using Visual Studio 2019

**Comment by titovmaxim** [comment]
I'n new here but I guess that crash is caused by the line in your code, namely:
(*grad)(0) = (*grad)(1) = (*grad)(2) = 0;

As you see your finctuin is invoked with grad = nullptr, so this assigment fails. And during the algorythm itself grad is used, so it is not nullptr during optimization steps.

I think it is better idea to check first if grad == nullptr and try to initialize it only when it exists. Not all algorythms use grad so will be nullptr even during optimization steps for let's say optim::nm() or optim::de() algorythms.

**Comment by Davar1990** [comment]
Thanks for your comment. I'm not using this library at the moment anymore but for the sake of the argument, that line `(*grad)(0) = (*grad)(1) = (*grad)(2) = 0;` is actually what causes the problem. However, it doesn't happen in the beginning. The algorithm I'm using uses grad and everything seems fine in the first few iteration. But after a few iterations the pointer grad becomes nullptr and if I comment out the line `settings_inp->opt_fn_value = opt_objfn(x_p,nullptr,opt_data);` in the file `error_reporting.ipp`, the grad pointer never becomes nullptr and everything works just fine.

**Comment by kthohr** [comment]
@titovmaxim is correct; you need to adjust your code to include a check if `grad` is null or otherwise.
