### ISSUE TITLE
Using header-only-version with Eigen failed to compile

### ISSUE THREAD

**Issue by lshok** [kthohr/optim#29]
System: macOS
Compile cmd: **g++  -DOPTIM_ENABLE_EIGEN_WRAPPERS --std=c++11  aa.cpp -I./header_only_version/  -I ./eigen-3.3.8/**

compiler output:
In file included from aa.cpp:1:
In file included from ./header_only_version/optim.hpp:51:
./header_only_version/unconstrained/nm.hpp:201:45: error: no matching function for call to object of type 'optim::Vec_t' (aka 'Matrix<double, Dynamic, 1>')
        simplex_fn_vals = OPTIM_MATOPS_EVAL(simplex_fn_vals(sort_vec));
                                            ^~~~~~~~~~~~~~~
./header_only_version/misc/matrix_ops/eval.hpp:30:35: note: expanded from macro 'OPTIM_MATOPS_EVAL'
    #define OPTIM_MATOPS_EVAL(x) (x).eval()
                                  ^
./eigen-3.3.8/Eigen/src/Core/DenseCoeffsBase.h:423:5: note: candidate function not viable: no known conversion from 'optim::VecInt_t' (aka 'Matrix<int, Dynamic, 1>') to 'Eigen::Index' (aka 'long') for 1st argument
    operator()(Index index)
    ^
./eigen-3.3.8/Eigen/src/Core/DenseCoeffsBase.h:178:5: note: candidate function not viable: no known conversion from 'optim::VecInt_t' (aka 'Matrix<int, Dynamic, 1>') to 'Eigen::Index' (aka 'long') for 1st argument
    operator()(Index index) const
    ^
./eigen-3.3.8/Eigen/src/Core/DenseCoeffsBase.h:115:41: note: candidate function not viable: requires 2 arguments, but 1 was provided
    EIGEN_STRONG_INLINE CoeffReturnType operator()(Index row, Index col) const
                                        ^
./eigen-3.3.8/Eigen/src/Core/DenseCoeffsBase.h:362:5: note: candidate function not viable: requires 2 arguments, but 1 was provided
    operator()(Index row, Index col)
    ^
In file included from aa.cpp:1:
In file included from ./header_only_version/optim.hpp:51:
./header_only_version/unconstrained/nm.hpp:202:44: error: no member named 'all' in namespace 'Eigen'
        simplex_points = OPTIM_MATOPS_EVAL(OPTIM_MATOPS_ROWS(simplex_points, sort_vec));
                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./header_only_version/misc/matrix_ops/access.hpp:35:50: note: expanded from macro 'OPTIM_MATOPS_ROWS'
    #define OPTIM_MATOPS_ROWS(x, v) (x)(v,Eigen::all) // v is a vector
                                          ~~~~~~~^
./header_only_version/misc/matrix_ops/eval.hpp:30:35: note: expanded from macro 'OPTIM_MATOPS_EVAL'
    #define OPTIM_MATOPS_EVAL(x) (x).eval()
                                  ^
aa.cpp:3:24: error: use of undeclared identifier 'arma'
double sphere_fn(const arma::vec& vals_inp, arma::vec* grad_out, void* opt_data)
                       ^
aa.cpp:3:45: error: use of undeclared identifier 'arma'
double sphere_fn(const arma::vec& vals_inp, arma::vec* grad_out, void* opt_data)
                                            ^
aa.cpp:5:22: error: use of undeclared identifier 'arma'
    double obj_val = arma::dot(vals_inp,vals_inp);
                     ^
aa.cpp:14:23: error: use of undeclared identifier 'arma'
double booth_fn(const arma::vec& vals_inp, arma::vec* grad_out, void* opt_data)
                      ^
aa.cpp:14:44: error: use of undeclared identifier 'arma'
double booth_fn(const arma::vec& vals_inp, arma::vec* grad_out, void* opt_data)
                                           ^
aa.cpp:36:5: error: use of undeclared identifier 'arma'
    arma::vec x = arma::ones(test_dim,1); // initial values (1,1,...,1)
    ^
aa.cpp:36:19: error: use of undeclared identifier 'arma'
    arma::vec x = arma::ones(test_dim,1); // initial values (1,1,...,1)
                  ^
aa.cpp:46:5: error: use of undeclared identifier 'arma'
    arma::cout << "lbfgs: solution to sphere test:\n" << x << arma::endl;
    ^
aa.cpp:46:63: error: use of undeclared identifier 'arma'
    arma::cout << "lbfgs: solution to sphere test:\n" << x << arma::endl;
                                                              ^
aa.cpp:51:5: error: use of undeclared identifier 'arma'
    arma::vec x_2 = arma::zeros(2,1); // initial values (0,0)
    ^
aa.cpp:51:21: error: use of undeclared identifier 'arma'
    arma::vec x_2 = arma::zeros(2,1); // initial values (0,0)
                    ^
aa.cpp:61:5: error: use of undeclared identifier 'arma'
    arma::cout << "lbfgs: solution to Booth test:\n" << x_2 << arma::endl;
    ^
aa.cpp:61:64: error: use of undeclared identifier 'arma'
    arma::cout << "lbfgs: solution to Booth test:\n" << x_2 << arma::endl;
                                                               ^
15 errors generated.

**Comment by titovmaxim** [comment]
I'm sure what aa.cpp is but it seems you have a mixture of wrappers: 'arma' is used inside you aa.cpp file and 'Eigen' wrapper is enabled by -D compiler option. Probably you should use then Eigen insted of 'arma' in your aa.cpp.

**Comment by lshok** [comment]
Thx for the reply, Titovmaxim, 
Indeed, my test main function used armadillo lib. The printed error message reflect this. However, I further commented all the code, except the include the  "optim.hpp" file, it still could not pass the compiling. Maybe I should not include optim.hpp, but more specific header?

**Comment by titovmaxim** [comment]
I guess you have to define a correct macro to include correct wrapper. Now you use -DOPTIM_ENABLE_EIGEN_WRAPPERS, which add an Eigen support to Optim library. Then in your code you use Armadilo, which leads to troubles.

I would suggest either to change compiler option to -DOPTIM_ENABLE_ARMA_WRAPPERS or just remove it at all and use #define OPTIM_ENABLE_ARMA_WRAPPERS prior to include optim.hpp.

**Comment by kthohr** [comment]
Don't mix Armadillo and Eigen.
