### ISSUE TITLE
settings parameters not working

### ISSUE THREAD

**Issue by osamazhar** [kthohr/optim#3]
Hi, 

I am running your example of pso with bounded values. I have notices that if I set:

settings.iter_max = 1;
settings.err_tol = 1000;
settings.opt_iter = 1;

Nothing works. The algorithm still runs for iterations more than 1, and it reaches the global minimum (when correct upper and lower bounds are set). I would like to stop the optimization loop at specific number of iterations. Can you help in this please?

**Comment by kthohr** [comment]
The number of 'iterations' in the PSO algorithm is set by `settings.pso_n_gen`. Try:
```cpp
settings.pso_n_gen = 1;
```

**Comment by osamazhar** [comment]
Hi,

Thanks for the reply. It didn't work. 

`Count: 200191
Obj Val: 0.2
Count: 200192
Obj Val: 2.10734e-08
Count: 200193
Obj Val: 2.10734e-08
Count: 200194
Obj Val: 2.10734e-08
Count: 200195
Obj Val: 0.2
Count: 200196
Obj Val: 2.10734e-08
Count: 200197
Obj Val: 2.10734e-08
Count: 200198
Obj Val: 0.2
Count: 200199
Obj Val: 0.2
Count: 200200
Obj Val: 2.35608e-08
Count: 200201
Obj Val: 2.10734e-08`

To make sure, I displayed the obj_val and number of times the algo runs. You can see it runs for 200201 times.

My settings are as follows:

settings.pso_center_particle = false;
settings.iter_max = 1;
settings.err_tol = 1000;
settings.opt_iter = 1;
settings.pso_n_gen = 1;
settings.vals_bound = true;

Please ignore unrealistic values, but I want to make it stop at either minimum obj_val or max number of iterations.

**Comment by kthohr** [comment]
Can you share the code you're using so I can replicate the error.

**Comment by osamazhar** [comment]
`#include "optim.hpp"

int count = 0;

double table_fn(const arma::vec& vals_inp, arma::vec* grad_out, void* opt_data)
{
    const double x = vals_inp(0);
    const double y = vals_inp(1);
    const double pi = arma::datum::pi;

    double obj_val = - std::abs( std::sin(x)*std::cos(y)*std::exp( std::abs(1.0 - std::sqrt(x*x + y*y)/pi) ) );
    //
    return obj_val;
}

double bukin_fn(const arma::vec& vals_inp, arma::vec* grad_out, void* opt_data)
{
    const double x = vals_inp(0);
    const double y = vals_inp(1);
    count ++;
    double obj_val = 100*std::sqrt(std::abs(y - 0.01*x*x)) + 0.01*std::abs(x + 10);
    // double obj_val = (1.5-x+x*y)*(1.5-x+x*y) + (2.25-x+x*y*y)*(2.25-x+x*y*y) + (2.625-x+(x*y*y*y))*(2.625-x+(x*y*y*y));
    //
    std::cout << "Count: " << count << std::endl;
    std::cout << "Obj_Val: " << obj_val << std::endl;

    return obj_val;
}

int main()
{
    //
    // Table function

    optim::algo_settings_t settings_1;

    settings_1.pso_center_particle = false;
    settings_1.vals_bound = true;
    settings_1.pso_n_gen = 10;
    //
    arma::vec x_1 = arma::zeros(2,1);

    settings_1.lower_bounds = arma::zeros(2,1) - 10;
    settings_1.upper_bounds = arma::zeros(2,1) + 10;

    double return_val;

    // Bukin function no. 6

    arma::vec x_2 = arma::zeros(2,1);
    x_2(0) = -9.5;
    x_2(1) = -9.5;

    double func_val;
    std::cout << "Value of X_2: " << x_2 << std::endl;
    bool success_2 = optim::pso(x_2,bukin_fn,nullptr, settings_1);
    return_val = settings_1.opt_value;
    if (success_2) {
        std::cout << "de: Bukin test completed successfully." << std::endl;
    } else {
        std::cout << "de: Bukin test completed unsuccessfully." << std::endl;
    }

    arma::cout << "de: solution to Bukin test:\n" << x_2 << arma::endl;

    std::cout << "Return Value from Optimization Algorithm is: " << return_val << std::endl;
    return 0;
}
`

This is the code I got from your website. I set pso_n_gen = 10 and my program runs for 1101 times before it stops.

**Comment by osamazhar** [comment]
Sorry for bad formatting, I am not really well aware of this formatting.

**Comment by kthohr** [comment]
I think you are confusing 'iterations' with function evaluations. One 'iteration' (or 'generation') in PSO terms involves multiple evaluations of the objective function. You can see this in the source code, but roughly speaking: 
- there are `settings.pso_n_pop`-number of function evaluations to initialize the algorithm, based on random sampling between the domain bounds. 
- For each generation up to `settings.pso_n_gen`, there are `settings.pso_n_pop`-number of additional function evaluations.
- There is also a final evaluation to check for errors and such before exiting the algorithm.

You see 1101 function calls because `settings.pso_n_pop = 100`  (by default); 100 relate to initialization, 1000 for the main algorithm run, and a final check for weird behavior.

**Comment by osamazhar** [comment]
Thanks for your reply. How to stop the optimization from iterating further if we reach a certain error tolerance range. I have tried setting err_tol to 1E-01, but the program keeps running until the combination of pop and gen finishes that gives me opt_value with less than 1E-32 or even 0 for simple problem.
