### ISSUE TITLE
Metaheuristic Optimization (DE, PSO) do not preserve vals_bound

### ISSUE THREAD

**Issue by titovmaxim** [kthohr/optim#31]
Setting Optim::algo_settings_t::vals_bound = true and setting lower_bounds & upper_bounds works well with ::ne() optimizer. The values are correctly resticted within the ranges defined.

Changeing optimizer to ::de() or ::pso() leads to results which are far out of the bounds defined. For example some values are restricted to 0.0 .. 1.0 range and results are in negative part.

Should ::de() & ::pso() preserve the limits? Are there some special requirements for that?

**Comment by titovmaxim** [comment]
Bag a pardon, was my bad. Everything works as expected.

P.S. Thank you for a very nice optimization library.

**Comment by izsahara** [comment]
Hi @titovmaxim , It seems Im facing the same problem with ::de and ::pso, did your solvers end up preserving the limits?
