### ISSUE TITLE
Different optimization results

### ISSUE THREAD

**Issue by kivicode** [kthohr/optim#32]
Hello,

I've faced a problem trying to optimize my cost function with the NM optimizer. The problem is that most of the time it returns true results, but sometimes they are wrong (still small but not right). I'm sure that the input data is the same (checked with hash functions) and I've set random seeds of both std and arma to 0 just to be sure. I have a guess that it somehow related to the fact that my cost function is really rough and there may take place a rounding error. How can I overcome the problem?

Thank you in advance!

**Comment by kthohr** [comment]
Do you have an example that you can share? Perhaps inspecting the optimization trace output (`settings.print_level = 3`) will help.
