### ISSUE TITLE
How do we disable the transforming of bounds/parameters (LBFGS with val_bounds)

### ISSUE THREAD

**Issue by izsahara** [kthohr/optim#37]
Ive noticed theres a (log) transformation of the bounds which causes my parameters to become negative, whereby my parameters are strictly positive and Ive implemented this transformation external to the optmizer.
In `lbfgs.hpp`

```
// Line 200
    if (vals_bound) { // should we transform the parameters?
        x = transform(x, bounds_type, lower_bounds, upper_bounds);
    }
```
I mean sure, I could comment it out, but is there an external way to disable this? without having to change the source code?
Thanks

**Comment by kthohr** [comment]
> How do we disable the transforming of parameters

By not enabling the `vals_bound` option through `optim::algo_settings_t settings`.
