### ISSUE TITLE
Incorrect sampling bounds?

### ISSUE THREAD

**Issue by Riley16** [kthohr/optim#39]
https://github.com/kthohr/optim/blob/a997b044695071fc1ab3e9f539656167fa22be29/src/unconstrained/de.cpp#L99

Unless I'm misreading something, it seems like the sampling bounds for DE are currently (0, (LB + (UB-LB))) = (0, UB) (while they should be (LB, UB) obviously). I think line 99 should be 

```
        X_next.row(i) = OPTIM_MATOPS_TRANSPOSE( par_initial_lb + OPTIM_MATOPS_HADAMARD_PROD( par_initial_ub - par_initial_lb, OPTIM_MATOPS_RANDU_VEC(n_vals) ) );
```

In addition, it'd be safer to enforce par_initial_ub =< upper_bound and par_initial_lb >= lower_bound if users are using upper and lower bounds. I'm getting NaN errors with non-zero upper and lower bounds after X_next is log-transformed for box constraining.

**Comment by kthohr** [comment]
Thanks for catching that bug. I've also implemented a bounds check as you suggested.
