### ISSUE TITLE
"err" not being updated

### ISSUE THREAD

**Issue by osamazhar** [kthohr/optim#4]
Hi,

I have observed that in optim/src/unconstrained/pso.cpp, in its loop line 143, the variable "err" is not being updated. This cause err_tol value inoperative, thus the loop never stops if error becomes less than err_tol. I assume it should be updated at line 201 by the following line:

err = global_best_val;

Please check and correct me if I am wrong. I have tried this and now err_tol values have an impact on the loop. I doubt, this issue is present in other algorithms too.

**Comment by kthohr** [comment]
`err` is difficult to define for metaheuristic algorithms; in convex optimization problems, we generally set `err` equal to the norm of the gradient vector, but the gradient need not be well-defined for these cases. 

The `err > err_tol` code was just a placeholder (to be defined later), but I've updated the PSO code to allow for checking the relative improvement in the global best objective function value every `pso_check_freq`-number of iterations. Try the new version and let me know if it behaves as expected. Note: `err` is not equal to the value of the objective function at the final iteration.
