### ISSUE TITLE
feature request: custom initialization of simplex for Nelder-Mead

### ISSUE THREAD

**Issue by mqnc** [kthohr/optim#44]
Hi!

I would like to be able to provide an initial simplex where I can consider some background information that I have about the optimization problem. I would also like to be able to stop the optimization, continue another optimization somewhere else and then pick up where I left, continuing from the last simplex.
Would you consider implementing this?
Otherwise I can fork the library and do it myself but it would be nicer to work with the official version :)

**Comment by mqnc** [comment]
I started writing my own Nelder Mead implementation so you can consider closing this. However, wikipedia also mentions that it is important to choose the initial simplex in order to fit the nature of the problem, so it might still be worth implementing.

**Comment by kthohr** [comment]
Implemented in version 2.1.0.
