### ISSUE TITLE
Getting error on MSVC - optim_options.hpp

### ISSUE THREAD

**Issue by suhasghorp** [kthohr/optim#48]
Hello,

Trying to compile the examples in VS 2022, C++17. Geting error C1017 - Invalid integer constant expression in optim_options.hpp at line 78.
The error is somewhere in this block. Based on MS documentation about this error at [C1017](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/fatal-error-c1017?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(C1017)%26rd%3Dtrue&view=msvc-170)
 it says : Constants defined using #define must have values that evaluate to an integer constant if they are used in an #if, #elif, or #else directive.
Any idea how to fix this?

Thank you.

// floating point number type

#ifndef OPTIM_FPN_TYPE
    #define OPTIM_FPN_TYPE double
#endif

#if OPTIM_FPN_TYPE == float //this is line 78
    #undef OPTIM_FPN_SMALL_NUMBER
    #define OPTIM_FPN_SMALL_NUMBER fp_t(1e-05)
#elif OPTIM_FPN_TYPE == double
    #undef OPTIM_FPN_SMALL_NUMBER
    #define OPTIM_FPN_SMALL_NUMBER fp_t(1e-08)
#else
    #error floating-point number type must be 'float' or 'double'
#endif

**Comment by kthohr** [comment]
Windows-based builds are not supported.
