### ISSUE TITLE
Add per-iteration best-fit result reporting

### ISSUE THREAD

**Issue by joncage** [kthohr/optim#5]
I wondered if you’d have any suggestions as to how to report the best guess at each iteration of the fitting loop for your NelderMead implementation? I'm interested for the purpose of investigating how our solution space is being explored but simply reporting `simplex_points.row(0)` (from my understanding that is the current lowest-error guess?) does not appear to yield the same results that are returned for the final iteration at the end of the method.

How easy would a feature that enables this diagnostic ability be to implement?

**Comment by kthohr** [comment]
Should be simple to implement. Would you like an iteration-by-iteration print of the minimum value of the objective function?

**Comment by joncage** [comment]
Exactly; for the minimum objective, if we could call a method to report:

* Iteration number
* The error from the objective function
* The inputs to the objective function that give that error value

**Comment by kthohr** [comment]
I just pushed a rough implementation of function tracing. You can use
```cpp
settings.verbose_print_level
```
to set the level of detail.

* `settings.verbose_print_level = 0`: default (no print)
* `settings.verbose_print_level = 1` print iteration number, current optimal value of the objective function and corresponding vertex
* `settings.verbose_print_level = 2` print iteration number, current optimal value of the objective function, objective function values for all vertices, and the full vertex matrix.
