### ISSUE TITLE
error configure header-only

### ISSUE THREAD

**Issue by Optiuse** [kthohr/optim#51]
When i try to create the Header-only Library i get this error: "error: unrecognized linear algebra library". Eigen is installed.
I installed the eigen library 3.4.0 via cmake/make install on debian. Eigen exist in folder /usr/local/include/eigen3/
Any idea to solve the problem? Thanks.

**Comment by kthohr** [comment]
I cannot replicate this error on my end. Running:

```bash
./configure --header-only-version
```

does not require you to specify a backend linear algebra library.
