### ISSUE TITLE
Error in header-only-library

### ISSUE THREAD

**Issue by JeffHough** [kthohr/optim#52]
After configuring to `header-only-library` version, there are include path errors in `misc/optim_misc.hpp`.

Currently, the first two includes are
```
// structs
#include "misc/optim_structs.hpp"

// trace
#include "misc/optim_trace.hpp"
```

Which gives include errors when compiling. The errors are fixed by changing these lines to:
```
// structs
#include "optim_structs.hpp"

// trace
#include "optim_trace.hpp"
```

**Comment by kthohr** [comment]
I cannot replicate this error. The folder structure seems correct to me.
