### ISSUE TITLE
BaseMatrixOps is empty when installing header files only

### ISSUE THREAD

**Issue by osorensen** [kthohr/optim#55]
When trying to install with header files only, the directory `BaseMatrixOps` is empty. The following shell command demonstrates the issue, since the last `ls` statement shows that the directory is empty.

```sh
git clone https://github.com/kthohr/optim.git && cd optim && \
./configure --header-only-version && ls header_only_version/BaseMatrixOps
```

This further causes the following error when trying to compile with `#include "optim.hpp"`

> fatal error: 'BaseMatrixOps/include/BaseMatrixOps.hpp' file not found
    #include "BaseMatrixOps/include/BaseMatrixOps.hpp"
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Presumably the error message occurs because of this line, i.e., `optim.hpp` requires the `BaseMatrixOps` directory to not be empty.

https://github.com/kthohr/optim/blob/d480ec82f97d8fcee9194afbce6b4e9a3cdeccb2/include/optim.hpp#L28

**Comment by kthohr** [comment]
The directory is empty because you did not run:

```
git submodule update --init
```
