### ISSUE TITLE
PSO center_particle

### ISSUE THREAD

**Issue by suzanamatos** [kthohr/optim#58]
First, I would like to thank you for making this library available.

However, I was trying to use the PSO method with upper and lower bounds.
For example, the Ackley function with 
```
X= [0.75 , 0.75]
Lower = [0.5, 0.5]
Upper = [1, 1]
```

After some tests I understood that I should send the pso_settings.initial_ub and pso_settings.initial_lb, because the default broke the bound limits.  So that was not a big issue. (I used  0.05 instead of  0.5)

However,  I think the center_particle option is a big issue with the bounds (At least in the initialize loop).
In line 147
```
 P.row(i) = BMO_MATOPS_COLWISE_SUM( BMO_MATOPS_MIDDLE_ROWS(P, 0, n_pop-2) ) / static_cast<fp_t>(n_pop-1); // center vector
```
It gets the center position of the particles using matrix P.
However, in line 162
```
if (vals_bound) {
      P.row(i) = transform<RowVec_t>(P.row(i), bounds_type, lower_bounds, upper_bounds);
}
```
The lines of  P are rewritten with some values  that   are not inside the bounds. 
So the center vector is not inside as well.

With the center_particle activated the results are very odd. After I deactivated it, the result is always good.

**Comment by kthohr** [comment]
Thanks for the bug report. I've updated the PSO code to fix a race condition as well. Should be working now.

**Comment by suzanamatos** [comment]
Thanks for the quick reply, however I updated the file here and I got the error:

`
Eigen::DenseCoeffsBase<Derived, 1>::Scalar& Eigen::DenseCoeffsBase<Derived, 1>::operator()(Eigen::Index) [with Derived = Eigen::Matrix<double, -1, 1>; Eigen::DenseCoeffsBase<Derived, 1>::Scalar = double; Eigen::Index = long int]: Assertion 'index >= 0 && index < size()' failed.
`

The debug shows that the problem is in line 253:
```
    objfn_vals(n_pop) = prop_objfn_val;
```

Here, `objfn_vals` is `200 x 1` and `n_pop = 200`.

**Comment by kthohr** [comment]
Oops! I resized `P` but not `objfn_vals`. Just pushed a fix.

**Comment by suzanamatos** [comment]
I don't know if this should happen, but...
With the center_particle activated I get something like this (it varies):

```
pso: Ackley test completed successfully.
pso: solution to Ackley test:
0.765738
0.732887
```

And when it isn't, I **aways** get:
```
pso: Ackley test completed successfully.
pso: solution to Ackley test:
0.968478
0.968478
```

And the objective functions are:
```
f(0.968478,0.968478) = 3.574
f(0.75,0.75) = 4.504
```

I don't really know the the PSO algorithm that well, so I didn't try to understand why the center particle is not helping as it should.

The exact test that I am doing is this:

```
double
ackley_fn(const Eigen::VectorXd& vals_inp, Eigen::VectorXd* grad_out, void* opt_data)
{
    const double x = vals_inp(0);
    const double y = vals_inp(1);

    const double obj_val = 20 + std::exp(1) - 20*std::exp( -0.2*std::sqrt(0.5*(x*x + y*y)) ) - std::exp( 0.5*(std::cos(2 * OPTIM_PI * x) + std::cos(2 * OPTIM_PI * y)) );
    return obj_val;
}
```


```
    Eigen::VectorXd x = 0.75 * Eigen::VectorXd::Ones(2);
    
    optim::algo_settings_t settings;
    settings.pso_settings.check_freq = 50;
    settings.vals_bound = true;
    settings.lower_bounds = 0.5* Eigen::VectorXd::Ones(2);
    settings.upper_bounds = 1 * Eigen::VectorXd::Ones(2);
    VectorXd boundsSize = settings.upper_bounds - settings.lower_bounds;
    settings.pso_settings.initial_lb = x -0.5* boundsSize;
    settings.pso_settings.initial_ub = x + 0.5* boundsSize;

    settings.pso_settings.center_particle = true;

    bool success = optim::pso(x, ackley_fn, nullptr, settings);

    if (success) {
        std::cout << "pso: Ackley test completed successfully." << std::endl;
    } else {
        std::cout << "pso: Ackley test completed UNsuccessfully." << std::endl;
    }

    std::cout << "pso: solution to Ackley test:\n" << x << std::endl;

    return 0;
```

**Comment by kthohr** [comment]
Just pushed another fix. Should work as expected now!

**Comment by suzanamatos** [comment]
Thank you! I everything think this time is working fine.
