### ISSUE TITLE
compilation probleme due to include path

### ISSUE THREAD

**Issue by Griset** [kthohr/optim#59]
Hi, 

I'm trying to install optim-master and I got the following error after the make command : 

g++ -std=c++14 -Wall -fPIC -march=native -O3 -ffp-contract=fast -flto -DNDEBUG -fopenmp -DOPTIM_FPN_TYPE=double -DOPTIM_ENABLE_EIGEN_WRAPPERS -I/usr/include/eigen3 -I./include src/line_search/more_thuente.cpp -c -o src/line_search/more_thuente.o
In file included from src/line_search/more_thuente.cpp:27:
./include/optim.hpp:28:14: fatal error: BaseMatrixOps/include/BaseMatrixOps.hpp: Aucun fichier ou dossier de ce type
     #include "BaseMatrixOps/include/BaseMatrixOps.hpp"
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:54: src/line_search/more_thuente.o] Error 1

I used the configure method and everything seems to be fine before : 

~/Outils/optim-master$ ./configure -i "/home/d07876/Outils/optim-master" -l eigen -p

OptimLib Configuration

Summary:
  - OS:            linux-gnu
  - Arch:          x86_64
  - C++ compiler:  g++
  - Build version: release

  - OPTIM_LINEAR_ALG_LIB set to: eigen
  - OPTIM_MATLIB_INCLUDE_PATH set to:
    /usr/include/eigen3
  - BLAS and Lapack libraries set to:
    -lblas -llapack

  - OpenMP features: enabled
  - floating-point number type: double
  - optimization flags:
    -fPIC -march=native -O3 -ffp-contract=fast -flto -DNDEBUG -fopenmp

  - OptimLib install path:
    /home/d07876/Outils/optim-master

  - Additional notes:

Configuration completed. Creating Makefile... done.

Could you tell me if I missed something during the installation 
Thank you

**Comment by kthohr** [comment]
Looks like you did not clone the BMO submodule. See here: https://github.com/kthohr/optim#installation-method-1-shared-library

```bash
# clone optim into the current directory
git clone https://github.com/kthohr/optim ./optim

# change directory
cd ./optim

# clone necessary submodules
git submodule update --init
```
