### ISSUE TITLE
How to use the library with real dynamic systems or async calls

### ISSUE THREAD

**Issue by patrickelectric** [kthohr/optim#6]
I'm trying to use this library with real dynamics systems, right now I'm facing a problem to use the API with this type of systems, because It the "optimized function" depends of a real hardware that takes time to answer and give a feedback for the next interaction. There is any plan to accomplish such thing with this library ?

**Comment by kthohr** [comment]
I'm afraid it is not clear to me what you're trying to do. Can you describe the problem in more detail, and/or provide a minimal code example?

**Comment by patrickelectric** [comment]
Hi Keith, sorry for not being clear. 
I can have a motor connected to an arduino controlling the speed set point, and I would like to use optim to optimize the control variables of that are in the arduino. 
Other example is PID running in a drone or a SITL environment, that I would like to optimize the stabilize time or the control cost.

**Comment by kthohr** [comment]
I'm not understanding the technical issue at play here. What feature would you like added or changed in order to facilitate this? Which optimizer are you trying to use for this?
