### ISSUE TITLE
Compile as a static library?

### ISSUE THREAD

**Issue by jussihi** [kthohr/optim#60]
Hello,

Thank you for the library, it works like a charm! :+1: 

Can the library be compiled and linked statically to my program?

**Comment by kthohr** [comment]
Not out of the box--you would need to modify `configure` and `Makefile` to do this. But perhaps a simpler approach would be to generate a header-only version of the library (`./configure --header-only-version`) and include the headers with your program (but at the likely cost of longer compile times and larger binaries).

**Comment by jussihi** [comment]
> Not out of the box--you would need to modify `configure` and `Makefile` to do this. But perhaps a simpler approach would be to generate a header-only version of the library (`./configure --header-only-version`) and include the headers with your program (but at the likely cost of longer compile times and larger binaries).

Thanks for confirming! I've been using `--header-only-version`, and will use it in the future.

I will close this issue as my question has been answered.

Once again, great library! Thanks a lot for the time and effort you've put in it!
