### ISSUE TITLE
After "./configure --header-only-version" the folder "header_only_version/BaseMatrixOps" is empty

### ISSUE THREAD

**Issue by kznsq** [kthohr/optim#62]
MacOS 13.0.1

**Comment by kznsq** [comment]
I found this module later, maybe I haven't read the docs carefully enough before the installation, but I don't remember the reference to the BaseMatrixOps submodule. Thanks for the library, anyway!

**Comment by kthohr** [comment]
```bash
# clone optim into the current directory
git clone https://github.com/kthohr/optim ./optim

# change directory
cd ./optim

# clone necessary submodules
git submodule update --init
```

**Comment by kznsq** [comment]
Please note that the second option does not have this instruction:

# clone necessary submodules
git submodule update --init

Maybe it will be better to add some?

"Installation Method 2: Header-only Library

OptimLib is also available as a header-only library (i.e., without the need
to compile a shared library). Simply run configure with the
--header-only-version option:

./configure --header-only-version
"

Thanks!


ср, 8 лют. 2023 р. о 18:03 kthohr ***@***.***> пише:

**Comment by kthohr** [comment]
Cloning submodules is now such a basic concept/requirement that I assume it to be known by all who can invoke a compiler.
