### ISSUE TITLE
Trouble using optim and mcmc in same project

### ISSUE THREAD

**Issue by magnoliasci** [kthohr/optim#63]
I run into problems when I try to include optim.h and mcmc.h in the same cpp file.  I think it's happening because the #include guards in BaseMatrixOps.hpp prevent the inclusion of that code into the mcmc namespace isn mcmc_options.h.  Is there a way to fix this, short of refactoring a bunch of the library code?

**Comment by kthohr** [comment]
This sounds like poor design on my part :) I'll come up with a fix. Thanks for flagging

**Comment by kthohr** [comment]
Just pushed updates to all packages. Let me know if that doesn't fix it...
