### ISSUE TITLE
PSO parameter bounds causes error

### ISSUE THREAD

**Issue by Konrad1991** [kthohr/optim#8]
I‘m really a newbie to c++/Rcpp. Thus, I‘m not sure what causes my problem. I'm running a simulation in Rcpp using PSO to optimize parameter of an ode system in order to match my measured data.
If I use the PSO with an unbounded parameter space everything works fine. However, if the parameter space is restricted part of the parameter passed to the objective function are “nan“. Any suggestion what the problem could be?

Many thanks in advance for your help.

**Comment by kthohr** [comment]
This is probably a scaling issue. I will check this weekend.

**Comment by kthohr** [comment]
Can you give me an idea of what the parameter bounds look like in these cases, and how close the optimal solution is to these bounds?

**Comment by Konrad1991** [comment]
For each of the parameters I want to set an individual upper and lower bound. The size of the parameters differ between 0.001 and ca. 121. Thus, it is not possible to set the same boundaries for all of them (If I set the same parameter boundaries for all of the parameter my program works). 

Some of the parameters are at lower or upper bound at the optimal solution. Do you need any further information?

**Comment by foxymop** [comment]
I have run into similar issues using optim::pso with bounds on the parameters. To test the PSO algorithm I wrote a simple objective function which returns the volume of a box. If I run the PSO with no bounds on the input vector the algorithm returns a vector with an element sufficiently close to zero. However, when I run the algorithm with lower bounds on the box dimensions I get an answer which is repeatable but nowhere near the analytical global minimum.
